### ISSUE TITLE
Chrome failed to start error in CentosOS

### ISSUE THREAD

**Issue by saravana87** [TokenMarketNet/ico#108]
Hi I have managed to install all the tools in CentoOS 7
While deploying contract i am facing following error. (I have installed headless google chrome https://intoli.com/blog/installing-google-chrome-on-centos/ and tried to chromedriver too.)

(venv) [root@localhost ico]# deploy-contracts --deployment-name testnet --deployment-file Testcontract.yaml --address 0x9f52e1360994dd5d490ac4a36b0f8cc04f19bb20
Web3 provider is RPC connection http://127.0.0.1:8545
Owner address is 0x9f52e1360994dd5d490ac4a36b0f8cc04f19bb20
Owner balance is 99.938819608 ETH
Already deployed contract, team_multisig 0x40a05d4ce308bf600cb275d7a3e9113518f59c54
Starting PresaleFundCollector deployment, with arguments  {'_owner': '0x40a05d4ce308bf600cb275d7a3e9113518f59c54', '_freezeEndsAt': 1520150241, '_weiMinimumLimit': 750000000000000000000}
PresaleFundCollector address is 0x790d8d2cd5fb2ff7002077cb1551cc97b1aed1f9
PresaleFundCollector constructor arguments payload is 0x00000000000000000000000040a05d4ce308bf600cb275d7a3e9113518f59c54000000000000000000000000000000000000000000000000000000005a9ba6e1000000000000000000000000000000000000000000000028a857425466f80000
PresaleFundCollector libraries are {'SafeMathLib': '0xdbe82b9bbfb91604fe44fb1275a40c2a6b753dc3'}
Expanding source code file PresaleFundCollector.sol
Expanding source code file ./Crowdsale.sol
Expanding source code file ./SafeMathLib.sol
Expanding source code file ./PricingStrategy.sol
Expanding source code file ./FinalizeAgent.sol
Expanding source code file ./FractionalERC20.sol
Expanding source code file zeppelin/contracts/token/ERC20.sol
Expanding source code file ./ERC20Basic.sol
Expanding source code file ./CrowdsaleBase.sol
Expanding source code file ./Haltable.sol
Expanding source code file zeppelin/contracts/ownership/Ownable.sol
Traceback (most recent call last):
  File "/token/ico/venv/bin/deploy-contracts", line 11, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-contracts')()
  File "/token/ico/venv/lib64/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/token/ico/venv/lib64/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/token/ico/venv/lib64/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/token/ico/venv/lib64/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/token/ico/ico/cmd/deploycontracts.py", line 29, in main
    deploy_crowdsale_from_file(project, deployment_file, deployment_name, address)
  File "/token/ico/ico/deploy.py", line 286, in deploy_crowdsale_from_file
    return _deploy_contracts(project, chain, web3, yaml_filename, chain_data, deploy_address)
  File "/token/ico/ico/deploy.py", line 270, in _deploy_contracts
    runtime_data, statistics, contracts = deploy_crowdsale(project, chain, yaml_filename, chain_data, deploy_address)
  File "/token/ico/ico/deploy.py", line 150, in deploy_crowdsale
    optimizer_runs=int(solc["optimizations"]["runs"])
  File "/token/ico/ico/etherscan.py", line 56, in verify_contract
    with Browser(driver_name=browser_driver) as browser:
  File "/token/ico/venv/lib64/python3.6/site-packages/splinter/browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File "/token/ico/venv/lib64/python3.6/site-packages/splinter/driver/webdriver/chrome.py", line 35, in __init__
    self.driver = Chrome(chrome_options=options, **kwargs)
  File "/token/ico/venv/lib64/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/token/ico/venv/lib64/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/token/ico/venv/lib64/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/token/ico/venv/lib64/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/token/ico/venv/lib64/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 3.10.0-693.2.2.el7.x86_64 x86_64)

**Comment by miohtama** [comment]
Please report to issue to Python WebDriver project in upstream, as this usually means something is wrong with your OS  + Chrome + ChromeDriver set up. Alternatively you can just disable EtherScan verification in the configuration file to skip this step.

**Comment by saravana87** [comment]
Thank you, It seems working, (I added headless option as true in python file).

I am using testrpc to deploy contract.

It would be great if you can give me example YAML file.
