### ISSUE TITLE
Assertion error Verification: assert crowdsale.call().getState() == CrowdsaleState.PreFunding

### ISSUE THREAD

**Issue by saravana87** [TokenMarketNet/ico#118]
I almost deployed the contract after lot of workaround and finally stuck here.

Any idea about how to getstate of the crowdsale or fixing it

Verification: assert token.call().owner() == team_multisig.address
Verification: assert crowdsale.call().owner() == team_multisig.address
Verification: assert preico.call().owner() == team_multisig.address
Verification: assert finalize_agent.call().teamMultisig() == team_multisig.address
Verification: assert finalize_agent.call().isSane()
Verification: assert crowdsale.call().getState() == CrowdsaleState.PreFunding
Traceback (most recent call last):
  File "/root/ico/ico/deploy.py", line 213, in exec_lines
    exec(buffer, context)
  File "<string>", line 1, in <module>
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/ico/venv/bin/deploy-contracts", line 9, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-contracts')()
  File "/root/ico/venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/root/ico/venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/ico/venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/ico/venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/ico/venv/lib/python3.5/site-packages/click/core.py", line 87, in augment_usage_errors
    yield
  File "/root/ico/venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/ico/ico/cmd/deploycontracts.py", line 29, in main
    deploy_crowdsale_from_file(project, deployment_file, deployment_name, address)
  File "/root/ico/ico/deploy.py", line 286, in deploy_crowdsale_from_file
    return _deploy_contracts(project, chain, web3, yaml_filename, chain_data, deploy_address)
  File "/root/ico/ico/deploy.py", line 272, in _deploy_contracts
    perform_verify_actions(chain, runtime_data, contracts)
  File "/root/ico/ico/deploy.py", line 251, in perform_verify_actions
    exec_lines(verify_actions, context, print_prefix="Verification:")
  File "/root/ico/ico/deploy.py", line 215, in exec_lines
    raise RuntimeError("Failed when running: {}".format(buffer)) from e
RuntimeError: Failed when running: assert crowdsale.call().getState() == CrowdsaleState.PreFunding

**Comment by saravana87** [comment]
Am not sure but I gave crowd sale start date and end date within same day using time stamp and it seems to be fixed using allocated-token-sale-example.yml
