### ISSUE TITLE
ImportError: No module named ico.cmd.deploycontracts

### ISSUE THREAD

**Issue by robertbob987** [TokenMarketNet/ico#125]
I followed the tonkenketnet project documentation to install the ICO project and run the command, but there was a problem.
Help me, please.
`(venv) robert@robert-VirtualBox:~/ico$ sudo -H deploy-contracts --help
Traceback (most recent call last):
  File "/usr/local/bin/deploy-contracts", line 11, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-contracts')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 587, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2800, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named ico.cmd.deploycontracts
(venv) robert@robert-VirtualBox:~/ico$ `

**Comment by miohtama** [comment]
I do not think it says in any point of instructions that you need to use `sudo`. Please follow the instructions correctly.

**Comment by robertbob987** [comment]
I don't use `SUDO,` the result is the same
`(venv) robert@robert-VirtualBox:~/ico$ deploy-contracts --help
Traceback (most recent call last):
  File "/usr/local/bin/deploy-contracts", line 11, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-contracts')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 587, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2800, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named ico.cmd.deploycontracts
`
