### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

### ISSUE THREAD

**Issue by troowala** [TokenMarketNet/ico#135]
When trying to deploy a contract to the Mainnet im getting RemoteDisconnected , sometimes halfway through contract deployment and sometimes the contract wont even begin deploying and throws the below errors.

 Im using geth v1.8.11

Anyone else facing this issue ?

python3 ico/cmd/deploycontracts.py --deployment-file crowdsales/"RETRACTED INFO".yml --deployment-name "RETRACTED INFO" --address "RETRACTED INFO"
Web3 provider is RPC connection http://172.21.0.1:8545
Owner address is "RETRACTED INFO"
Owner balance is "RETRACTED INFO" ETH
Already deployed contract, team_multisig "RETRACTED INFO"
Starting BurnableCrowdsaleToken deployment, with arguments  {'_name': '"RETRACTED INFO"', '_symbol': '"RETRACTED INFO"', '_initialSupply': 0, '_decimals': 18, '_mintable': True}
BurnableCrowdsaleToken address is "RETRACTED INFO"
BurnableCrowdsaleToken constructor arguments payload is "RETRACTED INFO"
BurnableCrowdsaleToken libraries are {'SafeMathLib': '"RETRACTED INFO"'}
Writing partial report crowdsales/"RETRACTED INFO".partial-report.yml
Starting FlatPricing deployment, with arguments  {'_oneTokenInWei': 2500000000000}
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

**Comment by troowala** [comment]
issue seems to be restricted to 1.8.11 , v 1.8.3 gives timeout issue instead which can be addressed by increasing timeout values in populus
