### ISSUE TITLE
Error on deploy-token

### ISSUE THREAD

**Issue by gelinger777** [TokenMarketNet/ico#26]
Web3 provider is RPC connection http://127.0.0.1:8545
Deployer address is 0x9da61758eb87d3b71672bd95465c4ca67b806c1c
Deployer balance is 99.999999999996321721 ETH
Starting contract deployment
Contract address is 0x389cec0b5e2cb40eaaf24a8afe1cb667c05ad4e3
CrowdsaleToken constructor arguments is 0000000000000000000000009da61758eb87d3b71672bd95465c4ca67b806c1c00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000005f5e1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a4765766f726b20322e300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000034745560000000000000000000000000000000000000000000000000000000000
Setting release agent to 0x94d8ccc0a2ab1b92925ac0ba8af46729e5a25105
Traceback (most recent call last):
  File "/usr/local/bin/deploy-token", line 11, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-token')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mymaps/Desktop/ico/ico/cmd/deploytoken.py", line 84, in main
    txid = contract.transact(transaction).setReleaseAgent(release_agent)
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 806, in transact_with_contract_function
    transaction=transaction,
  File "/usr/local/lib/python3.5/dist-packages/web3/utils/decorators.py", line 12, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 678, in _prepare_transaction
    fn_kwargs,
  File "/usr/local/lib/python3.5/dist-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 717, in _encode_transaction_data
    fn_name, args, kwargs,
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 646, in _get_function_info
    fn_abi = cls._find_matching_fn_abi(fn_name, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 610, in _find_matching_fn_abi
    raise ValueError("No matching functions found")
ValueError: No matching functions found

**Comment by gelinger777** [comment]
Seems this is related to --release-agent parameter

 $ deploy-token --chain=mainnet  --address=0x9da61758eb87d3b71672bd95465c4ca67b806c1c    --name="Gevork 2.0" --symbol=GEV --release-agent=0x94d8ccc0a2ab1b92925ac0ba8af46729e5a25105  --supply=100000000

so when I have removed it, the deployment has worked as expected...

**Comment by gelinger777** [comment]
my fault. sleepless night and didn saw that contracts are not same .

**Comment by gelinger777** [comment]
See whats happening, when I am giving option  --releasing-agent when deploying i am getting

```
(venv) mymaps@mymaps-ThinkPad-E550:~/Desktop/ico$ deploy-token --name "GevToken" --symbol GE3 --address 0x0085f718c11E5fCaF7B25eAdCCBcD7144823a6A9  --release-agent 0x0085f718c11E5fCaF7B25eAdCCBcD7144823a6A9    --minting-agent 0x0085f718c11E5fCaF7B25eAdCCBcD7144823a6A9  --chain mainnet  --supply 100000000 --decimals 3
Web3 provider is RPC connection http://127.0.0.1:8545
Deployer address is 0x0085f718c11E5fCaF7B25eAdCCBcD7144823a6A9
Deployer balance is 1.592645268 ETH
Starting contract deployment
Contract address is 0xa9582a791312d8cd9fb92a455940e372e2ae2c07
CrowdsaleToken constructor arguments is 0000000000000000000000000085f718c11e5fcaf7b25eadccbcd7144823a6a900000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000174876e80000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000008476576546f6b656e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000034745330000000000000000000000000000000000000000000000000000000000
Setting release agent to 0x0085f718c11E5fCaF7B25eAdCCBcD7144823a6A9
Traceback (most recent call last):
  File "/usr/local/bin/deploy-token", line 11, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-token')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mymaps/Desktop/ico/ico/cmd/deploytoken.py", line 84, in main
    txid = contract.transact(transaction).setReleaseAgent(release_agent)
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 806, in transact_with_contract_function
    transaction=transaction,
  File "/usr/local/lib/python3.5/dist-packages/web3/utils/decorators.py", line 12, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 678, in _prepare_transaction
    fn_kwargs,
  File "/usr/local/lib/python3.5/dist-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 717, in _encode_transaction_data
    fn_name, args, kwargs,
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 646, in _get_function_info
    fn_abi = cls._find_matching_fn_abi(fn_name, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 610, in _find_matching_fn_abi
    raise ValueError("No matching functions found")
ValueError: No matching functions found

```


The same story is also with --minting-agent 


Starting contract deployment
Contract address is 0xc9d044db595c01599fc4398811e978700da579c3
CrowdsaleToken constructor arguments is 0000000000000000000000000085f718c11e5fcaf7b25eadccbcd7144823a6a900000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000174876e80000000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000008476576546f6b656e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000034745330000000000000000000000000000000000000000000000000000000000
Setting minting agent
Traceback (most recent call last):
  File "/usr/local/bin/deploy-token", line 11, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-token')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mymaps/Desktop/ico/ico/cmd/deploytoken.py", line 89, in main
    txid = contract.transact(transaction).setMintAgent(minting_agent, True)
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 806, in transact_with_contract_function
    transaction=transaction,
  File "/usr/local/lib/python3.5/dist-packages/web3/utils/decorators.py", line 12, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 678, in _prepare_transaction
    fn_kwargs,
  File "/usr/local/lib/python3.5/dist-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 717, in _encode_transaction_data
    fn_name, args, kwargs,
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 646, in _get_function_info
    fn_abi = cls._find_matching_fn_abi(fn_name, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 610, in _find_matching_fn_abi
    raise ValueError("No matching functions found")
ValueError: No matching functions found

**Comment by gelinger777** [comment]
closing this. Deploy-token is not good to use with release-agent .
