### ISSUE TITLE
deploy-token do we need geth and snyc all nodes before deploy?

### ISSUE THREAD

**Issue by senzacionale** [TokenMarketNet/ico#31]
> deploy-token --chain=ropsten --address=0x3c2d4e5eae8c4a31ccc56075b5fd81307b1627c6 --name="MikkoToken 2.0" --symbol=MOO --release-agent=0x3c2d4e5eae8c4a31ccc56075b5fd81307b1627c6  --supply=100000

Do we need to run geth before and sync all nodes? We always get exception connection refused ...

**Comment by miohtama** [comment]
I cannot help you if I do not see what exceptions you get or what kind of set up you are using. I kindly ask you to be more specific when communicating your issue over Internet.

**Comment by senzacionale** [comment]
Sorry here it is:

command from ropsten testnet for deployment
`
deploy-token --chain=ropsten --address=0x9d83f19190D5A70263684b56869417904F6F0f6F --name="TestToken 2.0" --symbol=TTO --release-agent=0x9d83f19190D5A70263684b56869417904F6F0f6F  --supply=100000`

error:
```

(venv) user@ubuntu:~/ETH/ico$ deploy-token --chain=ropsten --address=0x9d83f19190D5A70263684b56869417904F6F0f6F --name="TestToken 2.0" --symbol=TTO --release-agent=0x9d83f19190D5A70263684b56869417904F6F0f6F  --supply=100000
Web3 provider is RPC connection http://127.0.0.1:8546
Deployer address is 0x9d83f19190D5A70263684b56869417904F6F0f6F
Traceback (most recent call last):
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7fd3bd52d668>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 376, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8546): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fd3bd52d668>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/ETH/ico/venv/bin/deploy-token", line 9, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-token')()
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/ETH/ico/ico/cmd/deploytoken.py", line 50, in main
    print("Deployer balance is", from_wei(web3.eth.getBalance(address), "ether"), "ETH")
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/web3/utils/functional.py", line 14, in inner
    value = fn(*args, **kwargs)
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/web3/eth.py", line 120, in getBalance
    formatters.input_block_identifier_formatter(block_identifier),
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/web3/providers/manager.py", line 43, in request_blocking
    response_raw = self.provider.make_request(method, params)
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/web3/providers/rpc.py", line 52, in make_request
    **self.get_request_kwargs()
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/web3/utils/compat/compat_requests.py", line 21, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8546): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fd3bd52d668>: Failed to establish a new connection: [Errno 111] Connection refused',))
(venv) user@ubuntu:~/ETH/ico$

```

**Comment by villesundell** [comment]
Hello! To me it  seems lile you have a network connection issue, can you connect to your node with "geth" for instance?

**Comment by senzacionale** [comment]
sure it works without a problem

**Comment by villesundell** [comment]
Could you paste the geth command here with the arguments (if it does not contain sensitive information)?

**Comment by senzacionale** [comment]
sure, which one do you need?

**Comment by villesundell** [comment]
Please paste the Geth command that you used to verify the connection :)

**Comment by senzacionale** [comment]
Sorry for late response
`
 geth --testnet --rpc --datadir /home/user/ETH/data/testnet/`

Here I can test "ropsten" network and in etherscan I can then compare last block hash

I tested again and is still same error
```

 deploy-token --chain=ropsten --address=0xD816d5032469d234fBc34919D92fE0d47BF0C713 --name="MikkoToken 2.0" --symbol=MOO --release-agent=0xD816d5032469d234fBc34919D92fE0d47BF0C713  --supply=100000
Traceback (most recent call last):
  File "/home/user/ETH/ico/venv/bin/deploy-token", line 9, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-token')()
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/ETH/ico/ico/cmd/deploytoken.py", line 45, in main
    with project.get_chain(chain) as c:
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/populus/chain/geth.py", line 118, in __enter__
    self.geth.wait_for_ipc(60)
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/geth/geth.py", line 171, in wait_for_ipc
    _timeout.check()
  File "/home/user/ETH/ico/venv/lib/python3.5/site-packages/geth/utils/compat/compat_stdlib.py", line 73, in check
    raise self
geth.utils.compat.compat_stdlib.Timeout: 60 seconds
```

**Comment by gelinger777** [comment]
I recommend that you install Parity as node. Is so simple to work with.  Install it,and then make following 

 parity --chain=kovan 

then you can get free kovan ether using 

https://github.com/kovan-testnet/faucet

I use personally CURL method. Create a public gist and make a curl call , and it will send free 1 ether .

Which you can use ....

**Comment by miohtama** [comment]
Please edit `populus.json` to match your network configuration.
