### ISSUE TITLE
deploy-contracts: Could not deploy contract MilestonePricing: Incorrect argument count.  Expected '1'.  Got '3'

### ISSUE THREAD

**Issue by prudnitskiy** [TokenMarketNet/ico#32]
Hi there!

This error raise when using deploy-contracts with example.yml. I already add missing arguments to token contract but I can't understand how to fix this error. 

Full exception message below:
```CrowdsaleToken libraries are {'SafeMathLib': '0x5712bf5561f17cb4b75f73c898f7313eeee54d24'}
Starting MilestonePricing deployment, with arguments  {'_preicoPrice': 8000000000000000, '_milestones': [1500739200, 10000000000000000, 1501171200, 11000000000000000, 1501603200, 12000000000000000, 1503676800, 13000000000000000], '_preicoContractAddress': '0x9756c1836c09a25efc639588cab032b452e8f5fb'}
Traceback (most recent call last):
  File "/SafeRoot/ico/ico/deploy.py", line 64, in deploy_contract
    contract, txhash = chain.provider.deploy_contract(contract_name, deploy_transaction=transaction, deploy_kwargs=kwargs)
  File "~/virtualenv/lib/python3.5/site-packages/populus/contracts/provider.py", line 154, in deploy_contract
    kwargs=deploy_kwargs,
  File "~/virtualenv/lib/python3.5/site-packages/web3/contract.py", line 295, in deploy
    deploy_transaction['data'] = cls._encode_constructor_data(args, kwargs)
  File "~/virtualenv/lib/python3.5/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "~/virtualenv/lib/python3.5/site-packages/web3/contract.py", line 732, in _encode_constructor_data
    arguments = merge_args_and_kwargs(constructor_abi, args, kwargs)
  File "~/virtualenv/lib/python3.5/site-packages/eth_utils/string.py", line 71, in inner
    return fn(*text_args, **text_kwargs)
  File "~/virtualenv/lib/python3.5/site-packages/web3/utils/abi.py", line 152, in merge_args_and_kwargs
    len(args) + len(kwargs),
TypeError: Incorrect argument count.  Expected '1'.  Got '3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/virtualenv/bin/deploy-contracts", line 11, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-contracts')()
  File "~/virtualenv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "~/virtualenv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "~/virtualenv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/virtualenv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/SafeRoot/ico/ico/cmd/deploycontracts.py", line 22, in main
    deploy_crowdsale_from_file(project, deployment_file, deployment_name, address)
  File "/SafeRoot/ico/ico/deploy.py", line 263, in deploy_crowdsale_from_file
    return _deploy_contracts(project, chain, web3, yaml_filename, chain_data, deploy_address)
  File "/SafeRoot/ico/ico/deploy.py", line 247, in _deploy_contracts
    runtime_data, statistics, contracts = deploy_crowdsale(project, chain, chain_data, deploy_address)
  File "/SafeRoot/ico/ico/deploy.py", line 130, in deploy_crowdsale
    contracts[name] = deploy_contract(project, chain, deploy_address, expanded_contract_def, chain_name, need_unlock=need_unlock)
  File "/SafeRoot/ico/ico/deploy.py", line 66, in deploy_contract
    raise RuntimeError("Could not deploy contract {}, constructor arguments {}".format(contract_name, kwargs)) from e
RuntimeError: Could not deploy contract MilestonePricing, constructor arguments {'_preicoPrice': 8000000000000000, '_milestones': [1500739200, 10000000000000000, 1501171200, 11000000000000000, 1501603200, 12000000000000000, 1503676800, 13000000000000000], '_preicoContractAddress': '0x9756c1836c09a25efc639588cab032b452e8f5fb'}```

**Comment by gelinger777** [comment]
I have the same issue too...

**Comment by reddec** [comment]
see https://github.com/TokenMarketNet/ico/issues/33

**Comment by gelinger777** [comment]
@reddec  it does not help ... Are you sure you could deploy that particular contract?

**Comment by gelinger777** [comment]
@prudnitskiy  check the contract  code. You have to keep only 1 array of milestones, and set the last milestone price to 0 . Otherwise will not be deployed !!!!
