### ISSUE TITLE
deploy-contracts issue with arguments 

### ISSUE THREAD

**Issue by gelinger777** [TokenMarketNet/ico#33]
Used standard example.yml with switched off verification of contract

```
mymaps@mymaps-ThinkPad-E550:~/Desktop/ico$ deploy-contracts --deployment-name testnet --deployment-file crowdsales/example.yml  --address 0x0085f718c11E5fCaF7B25eAdCCBcD7144823a6A9
Web3 provider is RPC connection http://127.0.0.1:8545
Owner address is 0x0085f718c11E5fCaF7B25eAdCCBcD7144823a6A9
Owner balance is 0.752808516 ETH
Starting Wallet deployment, with arguments  {'_daylimit': 0, '_required': 2, '_owners': ['0x0044Eb0651586dF0176B682c71C6B81Fa56Df54B', '0x0085f718c11E5fCaF7B25eAdCCBcD7144823a6A9']}
Wallet address is 0xf679335b842330e5d1410c5201c2ed1b3284a1ca
Wallet constructor arguments payload is 0x00000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000044eb0651586df0176b682c71c6b81fa56df54b0000000000000000000000000085f718c11e5fcaf7b25eadccbcd7144823a6a9
Wallet libraries are {}
Starting PresaleFundCollector deployment, with arguments  {'_weiMinimumLimit': 750000000000000000000, '_owner': '0xf679335b842330e5d1410c5201c2ed1b3284a1ca', '_freezeEndsAt': 1503429100}
PresaleFundCollector address is 0x4cd0399f08e8b74112159822af0702a798c89bb2
PresaleFundCollector constructor arguments payload is 0x000000000000000000000000f679335b842330e5d1410c5201c2ed1b3284a1ca00000000000000000000000000000000000000000000000000000000599c81ec000000000000000000000000000000000000000000000028a857425466f80000
PresaleFundCollector libraries are {'SafeMathLib': '0x49e4b40c5e4ffba1f6ecffa23c3c4efa7f2ab25f'}
Starting CrowdsaleToken deployment, with arguments  {'_initialSupply': 0, '_name': 'Example-testnet', '_symbol': 'EXA'}
Traceback (most recent call last):
  File "/home/mymaps/Desktop/ico/ico/deploy.py", line 63, in deploy_contract
    contract, txhash = chain.provider.deploy_contract(contract_name, deploy_transaction=transaction, deploy_kwargs=kwargs)
  File "/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py", line 154, in deploy_contract
    kwargs=deploy_kwargs,
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 295, in deploy
    deploy_transaction['data'] = cls._encode_constructor_data(args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 732, in _encode_constructor_data
    arguments = merge_args_and_kwargs(constructor_abi, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/eth_utils/string.py", line 71, in inner
    return fn(*text_args, **text_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/web3/utils/abi.py", line 152, in merge_args_and_kwargs
    len(args) + len(kwargs),
TypeError: Incorrect argument count.  Expected '5'.  Got '3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/deploy-contracts", line 11, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-contracts')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 87, in augment_usage_errors
    yield
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mymaps/Desktop/ico/ico/cmd/deploycontracts.py", line 22, in main
    deploy_crowdsale_from_file(project, deployment_file, deployment_name, address)
  File "/home/mymaps/Desktop/ico/ico/deploy.py", line 258, in deploy_crowdsale_from_file
    return _deploy_contracts(project, chain, web3, yaml_filename, chain_data, deploy_address)
  File "/home/mymaps/Desktop/ico/ico/deploy.py", line 242, in _deploy_contracts
    runtime_data, statistics, contracts = deploy_crowdsale(project, chain, chain_data, deploy_address)
  File "/home/mymaps/Desktop/ico/ico/deploy.py", line 129, in deploy_crowdsale
    contracts[name] = deploy_contract(project, chain, deploy_address, expanded_contract_def, chain_name, need_unlock=need_unlock)
  File "/home/mymaps/Desktop/ico/ico/deploy.py", line 65, in deploy_contract
    raise RuntimeError("Could not deploy contract {}, constructor arguments {}".format(contract_name, kwargs)) from e
RuntimeError: Could not deploy contract CrowdsaleToken, constructor arguments {'_initialSupply': 0, '_name': 'Example-testnet', '_symbol': 'EXA'}

```

**Comment by reddec** [comment]
I am not contributor, but can help:
in `example.yml` (in your case), in section `token`, add field `_decimals` and `_mintable`.

You will get something like this:

```yaml
# ...
      token:
            contract_name: CrowdsaleToken
            contract_file: CrowdsaleToken.sol
            arguments:
                _name: The Sample Token
                _symbol: XXX
                _initialSupply: 100000
                _decimals: 8
                _mintable: false
# ...
```

But that's not all. Also remove all arguments except `_milestones` in `pricing_strategy` like here:

```yaml
# ...
pricing_strategy:
            contract_name: MilestonePricing
            contract_file: MilestonePricing.sol
            arguments:
                _milestones:
                    - 1492272000
                    - "{{ to_wei('0.010', 'ether') }}"
                    - 1492876800
                    - "{{ to_wei('0.011', 'ether') }}"
                    - 1493481600
                    - "{{ to_wei('0.012', 'ether') }}"
                    - 1494691200
                    - "{{ to_wei('0.013', 'ether') }}"
# ...
```

Looks like examples not updated for new interface ;-)

**Comment by gelinger777** [comment]
then i get ValueError: {'code': -32015, 'data': 'Internal("Requires higher than upper limit of 1000000000000")', 'message': 'Transaction execution error.'}

**Comment by gelinger777** [comment]
[]((venv) mymaps@mymaps-ThinkPad-E550:~/Desktop/taza/ico$ deploy-contracts --deployment-name testnet --deployment-file crowdsales/example.yml  --address 0x00d2be7F3866160F900DF954E8f032d20fC11e85
Web3 provider is RPC connection http://127.0.0.1:8545
Owner address is 0x00d2be7F3866160F900DF954E8f032d20fC11e85
Owner balance is 6.378808768 ETH
Starting MilestonePricing deployment, with arguments  {'_milestones': [1492272000, 10000000000000000, 1492876800, 11000000000000000, 1493481600, 12000000000000000, 1494691200, 13000000000000000]}
Traceback (most recent call last):
  File "/home/mymaps/Desktop/taza/ico/ico/deploy.py", line 64, in deploy_contract
    contract, txhash = chain.provider.deploy_contract(contract_name, deploy_transaction=transaction, deploy_kwargs=kwargs)
  File "/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py", line 154, in deploy_contract
    kwargs=deploy_kwargs,
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 298, in deploy
    txn_hash = cls.web3.eth.sendTransaction(deploy_transaction)
  File "/usr/local/lib/python3.5/dist-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/web3/eth.py", line 239, in sendTransaction
    transaction=formatted_transaction,
  File "/usr/local/lib/python3.5/dist-packages/web3/utils/transactions.py", line 47, in get_buffered_gas_estimate
    gas_estimate = web3.eth.estimateGas(gas_estimate_transaction)
  File "/usr/local/lib/python3.5/dist-packages/web3/utils/functional.py", line 14, in inner
    value = fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/web3/eth.py", line 282, in estimateGas
    [formatted_transaction],
  File "/usr/local/lib/python3.5/dist-packages/web3/providers/manager.py", line 51, in request_blocking
    raise ValueError(response["error"])
ValueError: {'message': 'Transaction execution error.', 'data': 'Internal("Requires higher than upper limit of 1000000000000")', 'code': -32015}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/deploy-contracts", line 11, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-contracts')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 87, in augment_usage_errors
    yield
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mymaps/Desktop/taza/ico/ico/cmd/deploycontracts.py", line 22, in main
    deploy_crowdsale_from_file(project, deployment_file, deployment_name, address)
  File "/home/mymaps/Desktop/taza/ico/ico/deploy.py", line 263, in deploy_crowdsale_from_file
    return _deploy_contracts(project, chain, web3, yaml_filename, chain_data, deploy_address)
  File "/home/mymaps/Desktop/taza/ico/ico/deploy.py", line 247, in _deploy_contracts
    runtime_data, statistics, contracts = deploy_crowdsale(project, chain, chain_data, deploy_address)
  File "/home/mymaps/Desktop/taza/ico/ico/deploy.py", line 130, in deploy_crowdsale
    contracts[name] = deploy_contract(project, chain, deploy_address, expanded_contract_def, chain_name, need_unlock=need_unlock)
  File "/home/mymaps/Desktop/taza/ico/ico/deploy.py", line 66, in deploy_contract
    raise RuntimeError("Could not deploy contract {}, constructor arguments {}".format(contract_name, kwargs)) from e
RuntimeError: Could not deploy contract MilestonePricing, constructor arguments {'_milestones': [1492272000, 10000000000000000, 1492876800, 11000000000000000, 1493481600, 12000000000000000, 1494691200, 13000000000000000]}
)

**Comment by sithu** [comment]
Check out the latest code and try again. That fixed the issue for me.

```shell
deploy-contracts --deployment-file=crowdsales/example.yml --deployment-name=testnet --address=0x000000000 
```

**Comment by gelinger777** [comment]
@sithu sorry but you dont get the problem I think.  and your --address  should be the owner address...  no 0x0000000

**Comment by marriva** [comment]
Hello, there is the problem maybe with yaml mapping

`Starting CrowdsaleToken deployment, with arguments  {'_symbol': 'EXA', '_decimals': 0, '_name': 'Example-testnet', '_initialSupply': 0, '_mintable': True}
CrowdsaleToken address is 0xb977b94659368a1c7b26d6ff553a095a0687347c
CrowdsaleToken constructor arguments payload is 0x00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000f4578616d706c652d746573746e6574000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000034558410000000000000000000000000000000000000000000000000000000000
CrowdsaleToken libraries are {'SafeMathLib': '0x5fb64f1524392abb2202c6f91a09b67445a75090'}
Traceback (most recent call last):
  File "/home/usr/venv/bin/deploy-contracts", line 9, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-contracts')()
  File "/home/usr/venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/usr/venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/usr/venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/usr/venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/usr/ico/ico/cmd/deploycontracts.py", line 22, in main
    deploy_crowdsale_from_file(project, deployment_file, deployment_name, address)
  File "/home/usr/ico/ico/deploy.py", line 263, in deploy_crowdsale_from_file
    return _deploy_contracts(project, chain, web3, yaml_filename, chain_data, deploy_address)
  File "/home/usr/ico/ico/deploy.py", line 247, in _deploy_contracts
    runtime_data, statistics, contracts = deploy_crowdsale(project, chain, chain_data, deploy_address)
  File "/home/usr/ico/ico/deploy.py", line 130, in deploy_crowdsale
    contracts[name] = deploy_contract(project, chain, deploy_address, expanded_contract_def, chain_name, need_unlock=need_unlock)
  File "/home/usr/ico/ico/deploy.py", line 53, in deploy_contract
    kwargs = dict(**contract_def["arguments"])  # Unwrap YAML CommentedMap
KeyError: 'arguments'`

Might it is wrong order in arguments?
`Starting CrowdsaleToken deployment, with arguments  {'_symbol': 'EXA', '_decimals': 0, '_name': 'Example-testnet', '_initialSupply': 0, '_mintable': True}`

It should be __name, _symbol, _initialSupply, _decimals, _mintable_ as I guess, am I wrong?


example.yml is

token:
            contract_name: CrowdsaleToken
            contract_file: CrowdsaleToken.sol
            arguments:
                _name: Example-testnet
                _symbol: EXA
                _initialSupply: 0
                _decimals: 0
                _mintable: true

**Comment by gelinger777** [comment]
the problem in milestone pricing that it should have last stage to be priced 0. Otherwise will not deploy.
