### ISSUE TITLE
Incorrect Argument Count

### ISSUE THREAD

**Issue by gelinger777** [TokenMarketNet/ico#34]
When I try to deploy particular contract I get 

```
deploy-token --chain=mainnet --address=0x0085f718c11E5fCaF7B25eAdCCBcD7144823a6A9 --contract-name=AllocatedCrowdsale  --name=Xtoken --symbol=XXY --supply=1000000 --decimals=8 --verify --release-agent=0x0085f718c11E5fCaF7B25eAdCCBcD7144823a6A9 
Web3 provider is RPC connection http://127.0.0.1:8545
Deployer address is 0x0085f718c11E5fCaF7B25eAdCCBcD7144823a6A9
Deployer balance is 0.561346092 ETH
Starting contract deployment
Traceback (most recent call last):
  File "/usr/local/bin/deploy-token", line 11, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-token')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mymaps/Desktop/ico/ico/cmd/deploytoken.py", line 73, in main
    contract, txhash = c.provider.deploy_contract(contract_name, deploy_transaction=transaction, deploy_args=args)
  File "/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py", line 154, in deploy_contract
    kwargs=deploy_kwargs,
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 295, in deploy
    deploy_transaction['data'] = cls._encode_constructor_data(args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 732, in _encode_constructor_data
    arguments = merge_args_and_kwargs(constructor_abi, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/eth_utils/string.py", line 71, in inner
    return fn(*text_args, **text_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/web3/utils/abi.py", line 152, in merge_args_and_kwargs
    len(args) + len(kwargs),
TypeError: Incorrect argument count.  Expected '7'.  Got '4'

```

**Comment by gelinger777** [comment]
Just as a note, seams the deploy-token command cannot deploy a specific smartr contract.  It can only deploy very good a CentrallyIssuedToken.sol . You will have to use deploy-contracts command with preconfigured .yml file which is in /crowdsales/ folder. see example.yml
