### ISSUE TITLE
New Repo Error

### ISSUE THREAD

**Issue by gelinger777** [TokenMarketNet/ico#38]
```
(venv) mymaps@mymaps-ThinkPad-E550:~/Desktop/taza/ico$ deploy-contracts --deployment-name testnet --deployment-file crowdsales/example.yml  --address 0x00d2be7F3866160F900DF954E8f032d20fC11e85
Web3 provider is RPC connection http://127.0.0.1:8545
Owner address is 0x00d2be7F3866160F900DF954E8f032d20fC11e85
Owner balance is 6.69832 ETH
Starting Wallet deployment, with arguments  {'_owners': ['0x00d2be7F3866160F900DF954E8f032d20fC11e85', '0x001684606978c3B5F50D8AEC9A98FC137209C196'], '_daylimit': 0, '_required': 1}
Traceback (most recent call last):
  File "/home/mymaps/Desktop/taza/ico/ico/deploy.py", line 64, in deploy_contract
    contract, txhash = chain.provider.deploy_contract(contract_name, deploy_transaction=transaction, deploy_kwargs=kwargs)
  File "/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py", line 150, in deploy_contract
    ContractFactory = self.get_contract_factory(contract_identifier)
  File "/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py", line 237, in get_contract_factory
    BaseContractFactory = self.get_base_contract_factory(contract_identifier)
  File "/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py", line 189, in get_base_contract_factory
    return get_base_contract_factory(contract_identifier, self.provider_backends)
  File "/usr/local/lib/python3.5/dist-packages/populus/contracts/provider.py", line 38, in get_base_contract_factory
    "from any of the configured backends".format(contract_identifier)
populus.contracts.exceptions.UnknownContract: No contract data was available for the contract identifier 'Wallet' from any of the configured backends

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/deploy-contracts", line 11, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-contracts')()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 87, in augment_usage_errors
    yield
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mymaps/Desktop/taza/ico/ico/cmd/deploycontracts.py", line 22, in main
    deploy_crowdsale_from_file(project, deployment_file, deployment_name, address)
  File "/home/mymaps/Desktop/taza/ico/ico/deploy.py", line 263, in deploy_crowdsale_from_file
    return _deploy_contracts(project, chain, web3, yaml_filename, chain_data, deploy_address)
  File "/home/mymaps/Desktop/taza/ico/ico/deploy.py", line 247, in _deploy_contracts
    runtime_data, statistics, contracts = deploy_crowdsale(project, chain, chain_data, deploy_address)
  File "/home/mymaps/Desktop/taza/ico/ico/deploy.py", line 130, in deploy_crowdsale
    contracts[name] = deploy_contract(project, chain, deploy_address, expanded_contract_def, chain_name, need_unlock=need_unlock)
  File "/home/mymaps/Desktop/taza/ico/ico/deploy.py", line 66, in deploy_contract
    raise RuntimeError("Could not deploy contract {}, constructor arguments {}".format(contract_name, kwargs)) from e
RuntimeError: Could not deploy contract Wallet, constructor arguments {'_owners': ['0x00d2be7F3866160F900DF954E8f032d20fC11e85', '0x001684606978c3B5F50D8AEC9A98FC137209C196'], '_daylimit': 0, '_required': 1}
```

**Comment by gelinger777** [comment]
oh, the multisig contract was from Parity and is  removed....  closing
