### ISSUE TITLE
Deploy-token script read timed out

### ISSUE THREAD

**Issue by vbaranov** [TokenMarketNet/ico#49]
MacOS Sierra 10.12.6
Parity 1.7 
Kovan chain

I try to test your examples from [docs](https://ico.readthedocs.io/en/latest/commands.html#deploy-token). Firstly, deploy-token script.

1. I've started Parity 1.7 with JSON RPC url `http://localhost:8545`
2. Added `kovan` chain with connection to this JSON RPC url to populus.json.
3. Run `deploy-token --chain=kovan --contract-name="CentrallyIssuedToken" --address=0x005364854d51A0A12cb3cb9A402ef8b30702a565  --name="TestToken" --symbol=MOO --supply=916 --decimals=0 --verify --verify-filename=CentrallyIssuedToken.sol`
4. Sign transaction
![screen shot 2017-08-21 at 17 38 15](https://user-images.githubusercontent.com/4341812/29524101-9f6031a4-8697-11e7-9d52-e40451454638.png)

The output in console is:

```
Web3 provider is RPC connection http://localhost:8545
Deployer address is 0x005364854d51A0A12cb3cb9A402ef8b30702a565
Deployer balance is 0.996728632 ETH
Traceback (most recent call last):
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=8545): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/bin/deploy-token", line 11, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-token')()
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/ico/cmd/deploytoken.py", line 53, in main
    if is_account_locked(web3, address):
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/populus/utils/accounts.py", line 15, in is_account_locked
    web3.eth.sign(account, 'simple-test-data')
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/web3/eth.py", line 262, in sign
    "eth_sign", [account, encode_hex(data)],
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/web3/providers/manager.py", line 27, in request_blocking
    response_raw = self.provider.make_request(method, params)
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/web3/providers/rpc.py", line 52, in make_request
    **self.get_request_kwargs()
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/web3/utils/compat/compat_requests.py", line 21, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8545): Read timed out. (read timeout=10)
```

**Comment by miohtama** [comment]
Please use `curl` command to demostrate that JSON-RPC API works. It seems to be a Parity issue / local issue with your computer.

Here are some examples https://github.com/ethereum/wiki/wiki/JSON-RPC#json-rpc-api-reference

**Comment by vbaranov** [comment]
@miohtama sure, I can confirm that JSON-RPC API works:
```
viktors-MacBook-Pro:~ viktor$ curl --data '{"method":"web3_clientVersion","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","result":"Parity//v1.7.0-beta-5f2cabd-20170727/x86_64-macos/rustc1.18.0","id":1}
viktors-MacBook-Pro:~ viktor$
```

Otherwise, how the script determined the balance of the wallet at the 3d line of output.

**Comment by miohtama** [comment]
Looking the output more carefully it crashes when Populus framework tries to unlock the account:

```
 File "/Users/viktor/Documents/HintsProjects/Test/TokenMarketNet_ico/venv/lib/python3.5/site-packages/populus/utils/accounts.py", line 15, in is_account_locked
    web3.eth.sign(account, 'simple-test-data')
```

This might be a new change in Parity. It might be waiting for a user input in Web UI. I suggest you see what happens if you run parity using `--unlock` command line switch and make sure the deploy account stays unlocked.

https://ethereum.stackexchange.com/questions/15349/parity-unlock-multiple-accounts-at-startup

**Comment by vbaranov** [comment]
@miohtama tnx. 
The issue was with unlocking of account in Parity. It seems, `deploy-token` cannot communicate with parity ui, if unlocking isn't enabled. I guess this issue can be closed.
