### ISSUE TITLE
Etherscan window closes abruptly after verification

### ISSUE THREAD

**Issue by jonasjuan** [TokenMarketNet/ico#92]
Deploying contracts > contract deployed > chrome opens > fills in fields > i do the not a robot thing > another window with the I'm not a robot thing > shows results(not verified) > managed to glimpse the problem > chrome closes > deploy contract stops 

Terminal shows this : 

Traceback (most recent call last):
  File "/home/default/ico/venv/bin/deploy-contracts", line 9, in <module>
    load_entry_point('ico', 'console_scripts', 'deploy-contracts')()
  File "/home/default/ico/venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/default/ico/venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/default/ico/venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/default/ico/venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/default/ico/ico/cmd/deploycontracts.py", line 31, in main
    deploy_crowdsale_from_file(project, deployment_file, deployment_name, address)
  File "/home/default/ico/ico/deploy.py", line 288, in deploy_crowdsale_from_file
    return _deploy_contracts(project, chain, web3, yaml_filename, chain_data, deploy_address)
  File "/home/default/ico/ico/deploy.py", line 272, in _deploy_contracts
    runtime_data, statistics, contracts = deploy_crowdsale(project, chain, yaml_filename, chain_data, deploy_address)
  File "/home/default/ico/ico/deploy.py", line 150, in deploy_crowdsale
    optimizer_runs=int(solc["optimizations"]["runs"])
  File "/home/default/ico/ico/etherscan.py", line 77, in verify_contract
    browser.find_by_name("ctl00$ContentPlaceHolder1$btnSubmit").click()
  File "/home/default/ico/venv/lib/python3.5/site-packages/splinter/driver/webdriver/__init__.py", line 563, in click
    self._element.click()
  File "/home/default/ico/venv/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/default/ico/venv/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "/home/default/ico/venv/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/home/default/ico/venv/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotVisibleException: Message: element not visible
  (Session info: chrome=63.0.3239.108)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.10.0-42-generic x86_64)

Want to debug but i can't really see the results properly before the window closes

**Comment by villesundell** [comment]
Hello @jonasjuan! Recently Etherscan introduced the robot thingie. I have a branch "feat/etherscan-captcha" which should be working with the current version, feel free to checkout. It's practically the same I am using at the moment. It is a temporary fix, and will be replaced later with a better one (hence it's not merged to master)

**Comment by jonasjuan** [comment]
@villesundell 
Cool! Where is it though?

**Comment by villesundell** [comment]
Here it is: https://github.com/TokenMarketNet/ico/tree/feat/etherscan-captcha :)
If you are using command line, you can just run: git checkout feat/etherscan-captcha
(When you are inside the "ico" directory)

**Comment by jonasjuan** [comment]
Cool. Thank you!

**Comment by jonasjuan** [comment]
@villesundell 

selenium.common.exceptions.ElementNotVisibleException: Message: element not visible

Is that suppose to happen?

**Comment by jonasjuan** [comment]
Nevermind. Kinda figured it out.
